apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: summit-wind-turbine-app-dev
  annotations:
    argocd/app-name: summit-wind-turbine-app-dev
    backstage.io/kubernetes-id: summit-wind-turbine-app
    backstage.io/kubernetes-namespace: summit
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: WindTurbineInc/summit-wind-turbine
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.wearedevs.rl97.p1.openshiftapps.com/dev-pipelines/ns/summit/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.wearedevs.rl97.p1.openshiftapps.com/k8s/ns/summit/deployments/summit-wind-turbine-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.wearedevs.rl97.p1.openshiftapps.com/#https://github.com/WindTurbineInc/summit-wind-turbine?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/blues-man"
  providesApis: 
    - quinoa-wind-turbine-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: quinoa-wind-turbine-api
  description: API to register users
  links:
    - url: https://editor.swagger.io/
      title: Swagger UI
      icon: web
    - url: https://summit-wind-turbine-app-summit.apps.wearedevs.rl97.p1.openshiftapps.com/q/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/blues-man"
  definition:
    $text: https://summit-wind-turbine-app-summit.apps.wearedevs.rl97.p1.openshiftapps.com/q/openapi.yaml
